set -g mouse on

setw -g mode-keys vi

# Use Alt-arrow keys without prefix key to switch panes
bind -n S-M-Left select-pane -L
bind -n S-M-Right select-pane -R
bind -n S-M-Up select-pane -U
bind -n S-M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift up/down to switch sessions
bind -n S-Up switch-client -p
bind -n S-Down switch-client -n
